const TOTAL_DOC_LIMIT = 10;
const SESSION_COOKIE_MAX_AGE_HOUR = 1000 * 60 * 60; // 1 hour
const SESSION_COOKIE_MAX_AGE_DAYS = SESSION_COOKIE_MAX_AGE_HOUR * 24;

module.exports = {
    TOTAL_DOC_LIMIT,
    SESSION_COOKIE_MAX_AGE_DAYS
};
